zuul:
  sensitive-headers: 
  routes:
    first:
      path: /zhuhangjie/**
      serviceId: product
  ignored-patterns:
management:
  security:
    enabled: false
spring:
  redis:
    host: 106.14.3.142
    port: 6379
