
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Zhuhangjie_1
    url: jdbc:mysql://106.14.3.142:3306/sell?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
   jpa:
    show-sql: true
  rabbitmq:
    host: 106.14.3.142
    port: 5672
    username: guest
    password: guest
PRODUCT:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
env: zhuhangjie
label: master
