spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.14.3.142:3306/sell?characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
    username: root
    password: Zhuhangjie_1
  rabbitmq:
    host: 106.14.3.142
    port: 5672
    username: guest
    password: guest
  jpa:
    show-sql: true
